### ISSUE TITLE
can't use use-wallet library on heroku or netlify

### ISSUE THREAD

**Issue by noveltyz** [aragon/use-wallet#121]
[Heroku - v2 build log](https://github.com/aragon/use-wallet/files/7013282/Heroku.-.v2.build.log)

  108 |     __attribute__((deprecated(message))) declarator
             |                                          ^~~~~~~~~~
       In file included from ../src/HID.cc:34:
       ../src/HID.cc: At global scope:
       /app/.cache/node-gyp/14.17.5/include/node/node.h:758:43: warning: cast between incompatible function types from ‘void (*)(v8::Local<v8::Object>)’ to ‘node::addon_register_func’ {aka ‘void (*)(v8::Local<v8::Object>, v8::Local<v8::Value>, void*)’} [-Wcast-function-type]
         758 |       (node::addon_register_func) (regfunc),                          \\\n      |                                           ^
       /app/.cache/node-gyp/14.17.5/include/node/node.h:792:3: note: in expansion of macro ‘NODE_MODULE_X’
         792 |   NODE_MODULE_X(modname, regfunc, NULL, 0)  // NOLINT (readability/null_usage)
             |   ^~~~~~~~~~~~~
       ../src/HID.cc:646:3: note: in expansion of macro ‘NODE_MODULE’
         646 |   NODE_MODULE(HID, init);
             |   ^~~~~~~~~~~
         SOLINK_MODULE(target) Release/obj.target/HID-hidraw.node
       /usr/bin/ld: cannot find -lusb-1.0
       collect2: error: ld returned 1 exit status
       make: *** [HID-hidraw.target.mk:152: Release/obj.target/HID-hidraw.node] Error 1
       gyp ERR! build error 
       gyp ERR! stack Error: `make` failed with exit code: 2
       gyp ERR! stack     at ChildProcess.onExit (/tmp/build_f2ea8826/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
       gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
       gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:277:12)
       gyp ERR! System Linux 4.4.0-1094-aws
       gypmake: Leaving directory '/tmp/build_f2ea8826/node_modules/node-hid/build'
        ERR! command \"/tmp/build_f2ea8826/.heroku/node/bin/node\" \"/tmp/build_f2ea8826/.heroku/node/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
       gyp ERR! cwd /tmp/build_f2ea8826/node_modules/node-hid
       gyp ERR! node -v v14.17.5
       gyp ERR! node-gyp -v v5.1.0
       gyp ERR! not ok"

**Comment by WissenIstNacht** [comment]
Hey 👋🏼 🙂 

The logs say the build succeeded?

**Comment by noveltyz** [comment]
No, build isn't succeeded.

**Comment by danichts** [comment]
Check out [system dependencies](https://github.com/node-hid/node-hid#linux-kernel-26--install-examples-shown-for-debianubuntu) required by node-hid
